name: Docker Hub Publish

on:
  release:
    types: [released]

permissions:
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set version tag
        run:
          echo "GIT_TAG=$(git describe --candidates=0 --tags 2> /dev/null)" >> $GITHUB_ENV
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: embykeeper/embykeeper:latest,embykeeper/embykeeper:${{ env.GIT_TAG }}
